-- THIS FILE IS AUTO-GENERATED, WOULD BE OVERWRITTEN BY GUI-EDITOR
local component = require '@common.base.gui.component'
local bind = component.bind
local call = component.call
local gui_pkg = require '@common.base.gui.package'
local get_text = gui_pkg.get_text() or get_text
local on_player_prop = require '@common.base.gui.on_player_prop'
local on_unit_prop = require '@common.base.gui.on_unit_prop'
local ctrl_wrapper = require '@common.base.gui.ctrl_wrapper'


local lib_control = require '@lib_control.component'
local smallcard_unit_attr_panel = require '@smallcard_unit_attr_panel.component'
local gameui = require '@gameui.component'
local smallcard_inventory = require '@smallcard_inventory.component'
local smallcard_choose_one = require '@smallcard_choose_one.component'
local lib_game_options = require '@lib_game_options.component'

return gui_pkg.page_template {
    flatten_template = {
        ctrl_wrapper.panel {
            __EDIT_TIME = {
                lock = true,
            },
            layout = {
                grow_height = 1,
                grow_width = 1,
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
            },
            name = 'MainPage',
            show = true,
            z_index = 1,
        },0,
        lib_game_options.设置按钮 {
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 64,
                ratio = {},
                relative = {
                    [1] = -60,
                    [2] = 60,
                },
                row_self = 'end',
                width = 64,
            },
            name = '设置按钮1',
            show = false,
        },1,
        smallcard_inventory.背包入口 {
            layout = {
                ratio = {},
            },
            name = '背包入口2',
            show = false,
        },1,
        smallcard_unit_attr_panel.单位属性面板 {
            bind_unit = 0,
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 72.0,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = 1053.6806640625,
            },
            name = '单位属性面板3',
        },1,
        smallcard_choose_one.N选1_整体面板 {
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = 'N选1_整体面板2',
            show = true,
        },1,
        gameui.progress {
            default_box_margin = 10,
            default_name_width = 50,
            description = '',
            is_merge_text = true,
            is_name_show = true,
            is_name_show_real = true,
            layout = {
                col_self = 'end',
                height = 30,
                margin = {
                    bottom = 10,
                    left = 60,
                    right = 10,
                    top = 10,
                },
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 2300,
            },
            name = '经验条',
            name_height_prop = 20,
            name_pos_prop = 'left',
            name_show = true,
            name_width = 0,
            name_width_prop = 0,
            progress_bg_color = '#949494',
            progress_bg_image = '',
            progress_color = '#ff0000',
            progress_height = 20,
            progress_image = '',
            progress_text_show = true,
            progress_type = 'right',
            progress_width = 2300,
            show = false,
            value = 0,
            value_max = 20,
        },1,
        gameui.sci_2_rect {
            border = {
                bottom = 45,
                left = 45,
                right = 45,
                top = 45,
            },
            color = 'rgba(0, 0, 0, 0.7843)',
            decoration_image = '',
            decoration_layout_left = {
                row_self = 'start',
            },
            decoration_layout_right = {
                row_self = 'end',
            },
            image = '',
            is_decoration = false,
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 300,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 600,
            },
            name = '游戏结束面板',
            round_corner_radius = 20,
            show = false,
            style = 'image/rect/面板-西方1.png',
        },1,
        ctrl_wrapper.panel {
            color = 'rgba(255, 255, 255, 0.0000)',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 200,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 600,
            },
            name = '状态面板',
        },1,
        ctrl_wrapper.panel {
            color = 'rgba(255, 255, 255, 0.0000)',
            layout = {
                col_self = 'end',
                grow_height = 0.05,
                grow_width = 1,
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = '经验条Panel',
        },1,
        gameui.gf_3_major_btn {
            active_image = 'image/btn/sci_3_minor_active.png',
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            event = {
                on_click = call{client = '@@.gui.ui_response.效果开关',},
            },
            image = 'image/btn/sci_3_minor.png',
            layout = {
                col_self = 'start',
                height = 100,
                ratio = {},
                relative = {
                    [1] = 35.709838867188,
                    [2] = 233.75189208984,
                },
                row_self = 'start',
                width = 250,
            },
            name = '效果开关按钮',
            text = '关闭命中特效',
            text_color = '#CCCCCC',
            text_opacity = 1,
        },1,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '生命',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性icon (1).png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                ratio = {},
                relative = {
                    [1] = 222,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },4,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 100,
            bind_attr = '攻击',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性icon.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                ratio = {},
                relative = {
                    [1] = 60,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 1,
        },4,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '移动速度',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性icon (2).png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                ratio = {},
                relative = {
                    [1] = 384,
                    [2] = 0.0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },4,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 100,
            bind_attr = '急速',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性=魔法.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                ratio = {},
                relative = {
                    [1] = 546,
                    [2] = 0.0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 1,
        },4,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 100,
            bind_attr = '效果范围',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性=魔法.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                ratio = {},
                relative = {
                    [1] = 708,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 1,
        },4,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 100,
            bind_attr = '治疗倍率',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性=魔法.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                ratio = {},
                relative = {
                    [1] = 870,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 1,
        },4,
        ctrl_wrapper.label {
            font = {
                bold = true,
                color = 'rgba(192, 176, 155, 1.0000)',
                family = 'SourceHanSerif',
                size = 50,
            },
            layout = {
                col_self = 'start',
                height = 72,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 90,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'label1b',
            text = '选择技能',
        },5,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_choose_one/image/title_l.png',
            layout = {
                col_self = 'start',
                height = 32.0,
                ratio = {},
                relative = {
                    [1] = -432.0,
                    [2] = 110.0,
                },
                row_self = 'center',
                width = 550.0,
            },
            name = 'panel1a',
        },5,
        ctrl_wrapper.panel {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_choose_one/image/title_r.png',
            layout = {
                col_self = 'start',
                height = 32.0,
                ratio = {},
                relative = {
                    [1] = 432,
                    [2] = 110.0,
                },
                row_self = 'center',
                width = 551.0,
            },
            name = 'panel1a',
        },5,
        smallcard_choose_one.N选1_选择面板 {
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = 'N选1_选择面板5',
        },5,
        smallcard_choose_one.N选1_确认按钮 {
            border = {
                bottom = 25.130434782609,
                left = 29.565217391304,
                right = 29.565217391304,
                top = 14.782608695652,
            },
            image = '@smallcard_choose_one/image/button.png',
            layout = {
                col_self = 'end',
                height = 99.0,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -115,
                },
                row_self = 'center',
                width = 408.0,
            },
            name = 'N选1_确认按钮3',
            text = '确定',
        },5,
        smallcard_choose_one.N选1_关闭面板 {
            layout = {
                col_self = 'start',
                height = 48,
                ratio = {},
                relative = {
                    [1] = -100.0,
                    [2] = 100.0,
                },
                row_self = 'end',
                width = 48,
            },
            name = 'N选1_关闭面板4',
            show = false,
        },5,
        ctrl_wrapper.label {
            font = {
                align = 'center',
                line_height = 1,
                overflow = 'show',
                size = 80,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 200,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 500,
            },
            name = '游戏结束文字',
            text = '你赢了！',
        },7,
        ctrl_wrapper.panel {
            color = 'rgba(255, 255, 255, 0.0000)',
            image = '',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 160,
                ratio = {},
                relative = {
                    [1] = 20,
                    [2] = 0,
                },
                row_self = 'start',
                width = 160,
            },
            name = '状态面板',
        },8,
        ctrl_wrapper.panel {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            color = 'rgba(255,255,255,255)',
            image = 'image/group 26.png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 40,
                ratio = {},
                relative = {
                    [1] = 30.0,
                    [2] = 30.0,
                },
                row_self = 'start',
                width = 40,
            },
            name = '等级面板',
            z_index = 1,
        },8,
        ctrl_wrapper.panel {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            color = 'rgba(255,255,255,255)',
            image = 'image/血条背景.png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 28.0,
                ratio = {},
                relative = {
                    [1] = 180,
                    [2] = 60,
                },
                row_self = 'start',
                width = 372.0,
            },
            name = '血条背景',
        },8,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = 'image/经验条底.png',
            layout = {
                col_self = 'center',
                grow_height = 0.16666666666667,
                grow_width = 0.9,
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = '经验条背景',
        },9,
        ctrl_wrapper.label {
            font = {
                align = 'left',
                bold = true,
                size = 24,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'start',
                height = 30.0,
                ratio = {},
                relative = {
                    [1] = 119.0,
                    [2] = -13.0,
                },
                row_self = 'start',
                width = 140.85290527344,
            },
            name = '经验条文本',
            text = 'EXP：0%',
        },9,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                ratio = {},
                relative = {
                    [1] = -400,
                    [2] = -48.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },20,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                ratio = {},
                relative = {
                    [1] = 400,
                    [2] = -50,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },20,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -49.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },20,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                ratio = {},
                relative = {
                    [1] = 433,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
            show = false,
        },20,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                ratio = {},
                relative = {
                    [1] = 866,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
            show = false,
        },20,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = 'image/头像背景.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 160,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 160,
            },
            name = '头像背景',
            z_index = 0,
        },24,
        ctrl_wrapper.panel {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            color = 'rgba(255,255,255,255)',
            image = 'image/机器人头像.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = 130,
            },
            name = '头像填充',
            z_index = 1,
        },24,
        ctrl_wrapper.label {
            font = {
                bold = true,
                size = 24,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 40,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 40,
            },
            name = '等级文本',
            text = '1',
        },25,
        ctrl_wrapper.panel {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            color = 'rgba(255,255,255,255)',
            image = 'image/血条.png',
            layout = {
                col_self = 'center',
                grow_height = 0.78571428571429,
                grow_width = 1,
                margin = {
                    left = 4,
                    right = 4,
                },
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
            },
            name = '血条填充',
        },26,
        ctrl_wrapper.panel {
            border = {
                bottom = 0,
                left = 0,
                right = 14.402173913043,
                top = 0,
            },
            color = 'rgba(255,255,255,255)',
            image = 'image/经验条.png',
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 0.01,
                margin = {
                    left = 5,
                    right = 5,
                },
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
            },
            name = '经验条填充',
        },27,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 36,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = 200,
            },
            name = 'N选1_选项名称7',
        },29,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
            round_corner_radius = 100,
            show = true,
        },29,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },29,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 36,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = 200,
            },
            name = 'N选1_选项名称7',
        },30,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
            round_corner_radius = 100,
        },30,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },30,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 36,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = 200,
            },
            name = 'N选1_选项名称7',
        },31,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
            round_corner_radius = 100,
        },31,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
            text = '奖励描述奖励描述奖励描述奖励描述奖励描述奖',
        },31,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },32,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },32,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },32,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },33,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },33,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },33,
    }
}