{
    "ElementName":"FunctionDefine",
    "actions":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"If",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "conditions":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"FunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"FunctionDefine:CompareFunction",
                                    "packageName":"__common__",
                                    "s_or_c":"common"
                                }
                            },
                            "global":false,
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"字符串",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"string"
                                        },
                                        "value":"eq"
                                    },
                                    {
                                        "ElementName":"SourceValue",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "valueSource":{
                                            "ElementName":"Source",
                                            "targetUninit":{
                                                "id":"Variable:新变量:3814786159",
                                                "packageName":"__validator__",
                                                "s_or_c":"client"
                                            }
                                        }
                                    },
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"未定义",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"undefined"
                                        }
                                    }
                                ]
                            },
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        }
                    ]
                },
                "displayName":"",
                "falseActions":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "flags":{
                },
                "global":false,
                "trueActions":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"SetValue",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "global":false,
                            "left":{
                                "ElementName":"SourceValue",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "global":false,
                                "valueSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"Variable:新变量:3814786159",
                                        "packageName":"__validator__",
                                        "s_or_c":"client"
                                    }
                                }
                            },
                            "right":{
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "global":false,
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"布尔值",
                                    "flags":{
                                    },
                                    "global":false,
                                    "isType":true,
                                    "name":"boolean"
                                },
                                "value":true
                            }
                        }
                    ]
                }
            },
            {
                "ElementName":"If",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "conditions":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"FunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"FunctionDefine:CompareFunction",
                                    "packageName":"__common__",
                                    "s_or_c":"common"
                                }
                            },
                            "global":false,
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"字符串",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"string"
                                        },
                                        "value":"eq"
                                    },
                                    {
                                        "ElementName":"SourceValue",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "valueSource":{
                                            "ElementName":"Source",
                                            "targetUninit":{
                                                "id":"Variable:新变量:3814786159",
                                                "packageName":"__validator__",
                                                "s_or_c":"client"
                                            }
                                        }
                                    },
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"布尔值",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"boolean"
                                        },
                                        "value":true
                                    }
                                ]
                            },
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        }
                    ]
                },
                "displayName":"",
                "falseActions":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"FunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "caller":{
                                "ElementName":"SourceValue",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "global":false,
                                "s_or_c":"client",
                                "valueSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"PresetPropertyId:(Preset:游戏247595008, Linkspace:default, PresetKey:游戏)",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                }
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"Class:gameClass4146331648.0, MethodDefine:object_store_value",
                                    "packageName":"__client__",
                                    "s_or_c":"client"
                                }
                            },
                            "global":false,
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"SourceValue",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "valueSource":{
                                            "ElementName":"Source",
                                            "targetUninit":{
                                                "id":"Variable:ctrl:2783218722",
                                                "packageName":"__validator__",
                                                "s_or_c":"client"
                                            }
                                        }
                                    },
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"字符串",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"string"
                                        },
                                        "value":"Key"
                                    },
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"布尔值",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"boolean"
                                        },
                                        "value":true
                                    }
                                ]
                            },
                            "s_or_c":"client",
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        },
                        {
                            "ElementName":"SetValue",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "global":false,
                            "left":{
                                "ElementName":"Index",
                                "baseValue":{
                                    "ElementName":"SourceValue",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"",
                                    "flags":{
                                    },
                                    "global":false,
                                    "s_or_c":"client",
                                    "valueSource":{
                                        "ElementName":"Source",
                                        "targetUninit":{
                                            "id":"Variable:ctrl:2783218722",
                                            "packageName":"__validator__",
                                            "s_or_c":"client"
                                        }
                                    }
                                },
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "fromOop":true
                                },
                                "global":false,
                                "indexSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"Class:_OBJ_gameui_gui_ctrl_normal_btn, ClassProperty:text",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "s_or_c":"client"
                            },
                            "right":{
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "global":false,
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"字符串",
                                    "flags":{
                                    },
                                    "global":false,
                                    "isType":true,
                                    "name":"string"
                                },
                                "value":"关闭命中特效"
                            },
                            "s_or_c":"client"
                        },
                        {
                            "ElementName":"FunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"FunctionDefine:set_actor_creation_filter_level:2670198784",
                                    "packageName":"__client__",
                                    "s_or_c":"client"
                                }
                            },
                            "global":false,
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                            "enableDisplayName":true
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"数值",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"number"
                                        },
                                        "value":0
                                    }
                                ]
                            },
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        }
                    ]
                },
                "flags":{
                },
                "global":false,
                "s_or_c":"client",
                "trueActions":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"FunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "caller":{
                                "ElementName":"SourceValue",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "global":false,
                                "s_or_c":"client",
                                "valueSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"PresetPropertyId:(Preset:游戏247595008, Linkspace:default, PresetKey:游戏)",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                }
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"Class:gameClass4146331648.0, MethodDefine:object_store_value",
                                    "packageName":"__client__",
                                    "s_or_c":"client"
                                }
                            },
                            "global":false,
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"SourceValue",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "valueSource":{
                                            "ElementName":"Source",
                                            "targetUninit":{
                                                "id":"Variable:ctrl:2783218722",
                                                "packageName":"__validator__",
                                                "s_or_c":"client"
                                            }
                                        }
                                    },
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"字符串",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"string"
                                        },
                                        "value":"Key"
                                    },
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"布尔值",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"boolean"
                                        },
                                        "value":false
                                    }
                                ]
                            },
                            "s_or_c":"client",
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        },
                        {
                            "ElementName":"SetValue",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "global":false,
                            "left":{
                                "ElementName":"Index",
                                "baseValue":{
                                    "ElementName":"SourceValue",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"",
                                    "flags":{
                                    },
                                    "global":false,
                                    "s_or_c":"client",
                                    "valueSource":{
                                        "ElementName":"Source",
                                        "targetUninit":{
                                            "id":"Variable:ctrl:2783218722",
                                            "packageName":"__validator__",
                                            "s_or_c":"client"
                                        }
                                    }
                                },
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "fromOop":true
                                },
                                "global":false,
                                "indexSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"Class:_OBJ_gameui_gui_ctrl_normal_btn, ClassProperty:text",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "s_or_c":"client"
                            },
                            "right":{
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "global":false,
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"字符串",
                                    "flags":{
                                    },
                                    "global":false,
                                    "isType":true,
                                    "name":"string"
                                },
                                "value":"开启命中特效"
                            },
                            "s_or_c":"client"
                        },
                        {
                            "ElementName":"FunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"FunctionDefine:set_actor_creation_filter_level:2670198784",
                                    "packageName":"__client__",
                                    "s_or_c":"client"
                                }
                            },
                            "global":false,
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                            "enableDisplayName":true
                                        },
                                        "global":false,
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"数值",
                                            "flags":{
                                            },
                                            "global":false,
                                            "isType":true,
                                            "name":"number"
                                        },
                                        "value":1
                                    }
                                ]
                            },
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        }
                    ]
                }
            }
        ]
    },
    "breakPointInfo":{
        "disabled":false,
        "hasBreakPoint":false,
        "type":2
    },
    "defaultResetParameterCount":0,
    "description":"",
    "displayName":"func",
    "flags":{
        "hideConfig":true,
        "noSelf":true,
        "pop":true,
        "unchangeName":true,
        "unchangeParameter":true
    },
    "global":false,
    "id":"FunctionDefine:func:2022044573",
    "keyword":"",
    "label":"默认",
    "linkspace":"",
    "name":"func",
    "packageName":"__validator__",
    "parameters":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"ctrl",
                "flags":{
                    "fromOop":true
                },
                "global":false,
                "id":"Variable:ctrl:2783218722",
                "keyword":"",
                "name":"ctrl",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "global":false,
                    "isType":true,
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_gameui_gui_ctrl_normal_btn",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "tips":""
            },
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"mouse_btn_id",
                "flags":{
                },
                "global":false,
                "id":"Variable:mouse_btn_id:971499490",
                "keyword":"",
                "name":"mouse_btn_id",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"SimpleType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"数值",
                    "flags":{
                    },
                    "global":false,
                    "isType":true,
                    "name":"number"
                },
                "s_or_c":"client",
                "tips":""
            }
        ]
    },
    "rankOrder":0,
    "realReturnType":{
        "ElementName":"SimpleType",
        "breakPointInfo":{
            "disabled":false,
            "hasBreakPoint":false,
            "type":2
        },
        "displayName":"void",
        "flags":{
        },
        "global":false,
        "isType":true,
        "name":"void"
    },
    "s_or_c":"client",
    "subsections":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "tips":"",
    "typeParameters":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "uiText":"",
    "v2_version":0.400000,
    "variables":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Variable",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "defaultValue":{
                    "ElementName":"FunctionCall",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "caller":{
                        "ElementName":"SourceValue",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"",
                        "flags":{
                        },
                        "global":false,
                        "s_or_c":"client",
                        "valueSource":{
                            "ElementName":"Source",
                            "targetUninit":{
                                "id":"PresetPropertyId:(Preset:游戏247595008, Linkspace:default, PresetKey:游戏)",
                                "packageName":"__client__",
                                "s_or_c":"client"
                            }
                        }
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "funcSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:gameClass4146331648.0, MethodDefine:object_restore_value",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "global":false,
                    "parameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"SourceValue",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "global":false,
                                "valueSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"Variable:ctrl:2783218722",
                                        "packageName":"__validator__",
                                        "s_or_c":"client"
                                    }
                                }
                            },
                            {
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "global":false,
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"字符串",
                                    "flags":{
                                    },
                                    "global":false,
                                    "isType":true,
                                    "name":"string"
                                },
                                "value":"Key"
                            }
                        ]
                    },
                    "s_or_c":"client",
                    "typeParameters":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "displayName":"开关状态",
                "flags":{
                    "questionToken":true
                },
                "global":false,
                "id":"Variable:新变量:3814786159",
                "keyword":"",
                "name":"开关状态",
                "packageName":"__validator__",
                "rankOrder":0,
                "realType":{
                    "ElementName":"SimpleType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"布尔值",
                    "flags":{
                    },
                    "global":false,
                    "isType":true,
                    "name":"boolean"
                },
                "s_or_c":"client",
                "tips":""
            }
        ]
    }
}